
-- Add new columns to siswa table for the enhanced form
ALTER TABLE public.siswa 
ADD COLUMN IF NOT EXISTS umur integer,
ADD COLUMN IF NOT EXISTS mata_kanan text,
ADD COLUMN IF NOT EXISTS mata_kiri text,
ADD COLUMN IF NOT EXISTS ukuran_kepala numeric,
ADD COLUMN IF NOT EXISTS ukuran_pinggang numeric,
ADD COLUMN IF NOT EXISTS merokok_sekarang text,
ADD COLUMN IF NOT EXISTS merokok_jepang text,
ADD COLUMN IF NOT EXISTS minum_sake text,
ADD COLUMN IF NOT EXISTS penggunaan_tangan text DEFAULT 'Kanan',
ADD COLUMN IF NOT EXISTS buta_warna boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS warna_buta text,
ADD COLUMN IF NOT EXISTS bakat_khusus text,
ADD COLUMN IF NOT EXISTS kelebihan text,
ADD COLUMN IF NOT EXISTS kekurangan text,
ADD COLUMN IF NOT EXISTS pengalaman text,
ADD COLUMN IF NOT EXISTS minat text,
ADD COLUMN IF NOT EXISTS tujuan_jepang text,
ADD COLUMN IF NOT EXISTS target_menabung text,
ADD COLUMN IF NOT EXISTS tanggal_masuk_lpk date,
ADD COLUMN IF NOT EXISTS lama_belajar text,
ADD COLUMN IF NOT EXISTS catatan text,
ADD COLUMN IF NOT EXISTS is_available boolean DEFAULT true;
