// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxbeuezrppwvwxplnndk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4YmV1ZXpycHB3dnd4cGxubmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjM2MjEsImV4cCI6MjA2NjM5OTYyMX0.m5YQZYYZ75OaAS2jpDEvqGAuuM8ofaY8hmYbe6D1XDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});